
import { Passive } from "@/types/pal";

/**
 * Updated passive ability definitions based on actual in-game passives
 */
export const PASSIVE_DEFINITIONS: Record<number, Partial<Passive>> = {
  0x01: { name: "Work Speedster", description: "Increases work speed", rarity: "common" },
  0x02: { name: "Suntan Lover", description: "Higher efficiency during daytime", rarity: "common" },
  0x03: { name: "Artisan", description: "Improves product quality", rarity: "uncommon" },
  0x04: { name: "Positive Thinker", description: "Increases sanity recovery", rarity: "common" },
  0x05: { name: "Motivational Leader", description: "Boosts nearby allies' work speed", rarity: "rare" },
  0x06: { name: "Brave", description: "Less likely to become afraid", rarity: "uncommon" },
  0x07: { name: "Unstoppable", description: "Won't stop working even at low health", rarity: "rare" },
  0x08: { name: "Nimble", description: "Slightly faster movement", rarity: "common" },
  0x09: { name: "Logging Foreman", description: "Enhanced logging efficiency", rarity: "uncommon" },
  0x0A: { name: "Mining Foreman", description: "Enhanced mining efficiency", rarity: "uncommon" },
  0x0B: { name: "Planting Foreman", description: "Enhanced planting efficiency", rarity: "uncommon" },
  0x0C: { name: "Defensive", description: "Increased defense when guarding base", rarity: "rare" },
  0x0D: { name: "Power Conservationist", description: "Reduces electricity consumption", rarity: "rare" },
  0x0E: { name: "Serious", description: "Focuses intently on assigned work", rarity: "common" },
  0x0F: { name: "Ruthless", description: "Increased critical hit chance", rarity: "epic" },
  0x10: { name: "Legend", description: "Significantly enhances all abilities", rarity: "legendary" },
  // Additional passives from the game
  0x11: { name: "Workaholic", description: "Continues working without rest", rarity: "rare" },
  0x12: { name: "Musclehead", description: "Increased attack power but lower intelligence", rarity: "uncommon" },
  0x13: { name: "Diet Lover", description: "Consumes less food", rarity: "common" },
  0x14: { name: "Carefree", description: "Resistant to mental ailments", rarity: "uncommon" },
  0x15: { name: "Glutton", description: "Consumes more food but works faster", rarity: "uncommon" },
  0x16: { name: "Night Shift", description: "Higher efficiency during nighttime", rarity: "common" },
  0x17: { name: "Handy", description: "Better with tools and machinery", rarity: "rare" },
  0x18: { name: "Hard Worker", description: "Gains more experience from working", rarity: "rare" },
  0x19: { name: "Transporter", description: "Increases carrying capacity", rarity: "uncommon" },
  0x1A: { name: "Fragile", description: "Lower defense but higher work speed", rarity: "common" },
  0x1B: { name: "Healer", description: "Occasionally heals nearby allies", rarity: "rare" },
  0x1C: { name: "Aggressive", description: "More likely to attack enemies", rarity: "uncommon" },
  0x1D: { name: "Pacifist", description: "Less likely to engage in combat", rarity: "common" },
  0x1E: { name: "Collector", description: "Sometimes finds rare items", rarity: "rare" },
  0x1F: { name: "Lucky", description: "Increased chance of rare events", rarity: "epic" },
};

// Accurate Pal species definitions based on the actual game
export const PAL_DEFINITIONS: Record<number, string> = {
  0x01: "Lamball",
  0x02: "Cattiva",
  0x03: "Chikipi",
  0x04: "Lifmunk",
  0x05: "Foxparks",
  0x06: "Fuack",
  0x07: "Sparkit",
  0x08: "Tanzee",
  0x09: "Rooby",
  0x0A: "Pengullet",
  0x0B: "Penking",
  0x0C: "Chillet",
  0x0D: "Univolt",
  0x0E: "Foxcicle",
  0x0F: "Pyrin",
  0x10: "Reindrix",
  0x11: "Rayhound",
  0x12: "Kitsun",
  0x13: "Dazzi",
  0x14: "Lunaris",
  0x15: "Dinossom",
  0x16: "Grizzbolt",
  0x17: "Lovander",
  0x18: "Flambelle",
  0x19: "Vanwyrm",
  0x1A: "Bushi",
  0x1B: "Beakon",
  0x1C: "Ragnahawk",
  0x1D: "Katress",
  0x1E: "Wixen",
  0x1F: "Verdash",
  0x20: "Vaelet",
  0x21: "Sibelyx",
  0x22: "Eikthyrdeer",
  0x23: "Mammorest",
  0x24: "Melpaca",
  0x25: "Woolipop",
  0x26: "Mozzarina",
  0x27: "Bristla",
  0x28: "Gobfin",
  0x29: "Hangyu",
  0x2A: "Swee",
  0x2B: "Sweepa",
  0x2C: "Chunchee",
  0x2D: "Kingpaca",
  0x2E: "Arsox",
  0x2F: "Dumud",
  0x30: "Cawgnito",
  0x31: "Leezpunk",
  0x32: "Loupmoon",
  0x33: "Galeclaw",
  0x34: "Robinquill",
  0x35: "Gorirat",
  0x36: "Beegarde",
  0x37: "Elizabee",
  0x38: "Grintale",
  0x39: "Swampent",
  0x3A: "Firestirge",
  0x3B: "Cryolinx",
  0x3C: "Petallia",
  0x3D: "Azurobe",
  0x3E: "Cryolinx",
  0x3F: "Blazehowl",
  0x40: "Relaxaurus",
  0x41: "Tombat",
  0x42: "Troubark",
  0x43: "Quivern",
  0x44: "Helzephyr",
  0x45: "Astegon",
  0x46: "Menasting",
  0x47: "Anubis",
  0x48: "Jormuntide",
  0x49: "Wumpo",
  0x4A: "Frostallion",
  0x4B: "Necromus",
  0x4C: "Faleris",
  0x4D: "Orserk",
  0x4E: "Shadowbeak",
  0x4F: "Paladius",
  0x50: "Jetragon",
  // Additional pals
  0x51: "Jolthog",
  0x52: "Gumoss",
  0x53: "Vixy",
  0x54: "Hoocrates",
  0x55: "Teafant",
  0x56: "Depresso",
  0x57: "Cremis",
  0x58: "Daedream",
  0x59: "Surfent",
  0x5A: "Maraith",
  0x5B: "Fuddler",
  0x5C: "Killamari",
  0x5D: "Mau",
  0x5E: "Celaray",
  0x5F: "Direhowl",
  0x60: "Tocotoco",
  0x61: "Flopie",
  0x62: "Mozzarina",
  0x63: "Warsect",
  0x64: "Nitewing",
};

// Helper function for finding a Pal ID by name
export function getPalIdByName(name: string): number | null {
  const entry = Object.entries(PAL_DEFINITIONS).find(([_, palName]) => palName === name);
  return entry ? parseInt(entry[0], 16) : null;
}

// Helper function for finding a Passive ID by name
export function getPassiveIdByName(name: string): number | null {
  const entry = Object.entries(PASSIVE_DEFINITIONS).find(([_, passive]) => passive.name === name);
  return entry ? parseInt(entry[0], 16) : null;
}
